apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-depl
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        livenessProbe:
            exec:
              command:
              - sh
              - tmp/healthy.sh
            initialDelaySeconds: 20
            periodSeconds: 5
        ports:
        - containerPort: 21
        - containerPort: 20000
        - containerPort: 20001

---
apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
  - name: ftp-pasv1
    port: 21
  - name: ftp-pasv2
    port: 20000
  - name: ftp-pasv3
    port: 20001